carshare/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'carshare.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'corpcarshare.views.home'),
    url(r'^admin/', include(admin.site.urls)),
)

corpcarshare/models.py
from django.db import models
from django.utils.encoding import smart_unicode

class eachpost(models.Model):
	email = models.EmailField(max_length=70)
	date = models.DateTimeField(auto_now_add = True, auto_now = False)
	homezip = models.CharField(max_length = 5)
	workzip = models.CharField(max_length = 5)
	workaddr = models.CharField(max_length = 50)
	workname = models.CharField(max_length = 30)

	found = models.BooleanField()
	withdraw = models.BooleanField()

	def __unicode__(self):
		return smart_unicode(self.email)

class eachcompany(models.Model):
	compname = models.CharField(max_length = 30)
	compzip = models.CharField(max_length = 5)
	compaddr = models.CharField(max_length = 50)

	def __unicode__(self):
		return smart_unicode(self.compname)
	

# Create your models here.

corpcarshare/forms.py
from django import forms

from .models import eachpost, eachcompany
from django.forms.extras.widgets import SelectDateWidget


class eachpostform(forms.ModelForm):
	email = forms.EmailField(required = True, max_length=70, widget=forms.TextInput(attrs={ 'placeholder': ' corporate email required', 'class': 'form-control'}))
	homezip = forms.CharField(required = True, max_length = 5, widget=forms.TextInput(attrs={'class': 'form-control' }))
	workname = forms.CharField(required = True, max_length = 30, widget=forms.TextInput(attrs={'placeholder': ' your company name', 'class': 'form-control' }))
	workaddr = forms.CharField(required = True, max_length = 50, widget=forms.TextInput(attrs={'placeholder': ' your company address', 'class': 'form-control' }))
	workzip = forms.CharField(required = True, max_length = 5, widget=forms.TextInput(attrs={'class': 'form-control' }))
	class Meta:
		model = eachpost


class eachcompanyform(forms.ModelForm):
	compname = forms.CharField(required = True, max_length = 30)
	compzip = forms.CharField(required = True, max_length = 5)
	compaddr = forms.CharField(required = True, max_length = 50)
	
	class Meta:
		model = eachcompany

corpcarshare/views.py
from django.shortcuts import render, render_to_response, RequestContext
from django.http import HttpResponse

from .forms import eachpostform, eachcompanyform
from .models import eachpost, eachcompany

from django.views.generic import TemplateView
from django.views.generic.list import ListView, BaseListView

from django.views.generic import CreateView
from django.views.generic.edit import BaseCreateView
from django.views.generic.base import TemplateResponseMixin

from django.http import HttpResponse
from django.core.context_processors import csrf

import json
import urllib

from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage




# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the poll index.")


def home(request):
	if request.method == 'POST':
		form = eachpostform(request.POST)
		if form.is_valid():
			save_it = form.save(commit = False)
			save_it.save()
			Compname = request.POST.get('workname', None)
			Compaddr = request.POST.get('workaddr', None)
			Compzip = request.POST.get('workzip', None)
			comp_obj = eachcompany(compname = Compname, compzip = Compzip, compaddr = Compaddr)
			comp_obj.save()
			#send_mail('Your carpool candidates', 'Here is the message.', 'from@example.com', ['sywad87@gmail.com'], fail_silently=True) 
			#msg = EmailMessage('Request Callback','Here is the message.', to=['yiwei.song@sandisk.com'])
			#msg.send()
			results = eachpost.objects.all().order_by("-date")[:10]
			return render_to_response("corpcarshare.html", {'form': eachpostform(request.POST), 'object_list':results}, context_instance = RequestContext(request))

	else:
		form = eachpostform()
	content = match('95035', '94587')
	message = draftEmail(content)
	send_mail('Your carpool candidates', message, 'sywad87@gmail.com', ['sywad87@gmail.com'], fail_silently=True) 
	args = {}
	args.update(csrf(request))
	args['form'] = form 
	args['object_list'] = eachpost.objects.all().order_by("-date")[:10]
	companies = eachcompany.objects.all()
	name = []
	address = []
	for c in companies:
		#res.append(c.__unicode__())
		name.append(c.compname)
		address.append(c.compaddr)
	args['name'] = json.dumps(name)
	args['address'] = json.dumps(address)
	return render_to_response("corpcarshare.html", args, context_instance = RequestContext(request))




def nameauto(request):
    term = request.GET.get('term') #jquery-ui.autocomplete parameter
    names = eachcompany.objects.all() #lookup for a city
    res = []
    for c in names:
         #make dict with the metadatas that jquery-ui.autocomple needs (the documentation is your friend)
         #dict = {'id':c.id, 'label':c.__unicode__(), 'value':c.__unicode__()}
         #dict = {'label':c.__unicode__()}
         dict = c.__unicode__()
         res.append(dict)
    return HttpResponse(json.dumps(res), mimetype='application/json')


def distance(origin, destination):
	GEOCODE_BASE_URL = 'https://maps.googleapis.com/maps/api/distancematrix/json'
	url = GEOCODE_BASE_URL + '?' + 'origins='+origin + '&' + 'destinations=' + destination
	result = json.load(urllib.urlopen(url))
	status = result['rows'][0]['elements'][0]['status']
	if (status == 'OK'):
		return result['rows'][0]['elements'][0]['duration']['value']
	else:
		return 10000


def match(home, work):
	value = {}
	candidates = eachpost.objects.all()
	for candidate in candidates:
		#print candidate.workzip
		value[candidate] = distance(home, candidate.homezip) + distance(work, candidate.workzip)
		print value[candidate]
	target = min(value, key=value.get)
	result = [target.email, target.homezip, target.workzip]
	return result

def draftEmail(content):
	message = 'Here is your mate: ' + 'email: '+ content[0] + ' home address: ' + content[1] + ' work address: ' + content[2]
	return message

corpcarshare/templates/corpcarshare.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>Corpcarshare</title>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>

  <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.8/jquery.validate.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>


  <div class="container">

    <div class="header">
      <ul class="nav nav-pills pull-right">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <h3 class="text-muted">CarShare</h3>
    </div>


    <form class="form-horizontal" role="form" method = 'POST' action = ''> {% csrf_token %}



     <div class="form-group">

      {{ form.email.errors }}
      <h4><label for="email" class="col-sm-0 control-label">Email</label></h4>
      <h4>{{ form.email }}</h4>


    </div>


    <div class="form-group">

      {{ form.homezip.errors }}
      <h4><label for="homezip" class="col-sm-0 control-label">Home Zipcode</label></h4>
      <h4>{{ form.homezip }}</h4>


    </div>


    <div class="form-group">

      {{ form.workname.errors }}
      <h4><label for="workname" class="col-sm-0 control-label">Company Name</label></h4>
      <h4>{{ form.workname }}</h4>


      {{ form.workaddr.errors }}
      <h4><label for="workaddr" class="col-sm-0 control-label">Company Addresss</label></h4>
      <h4>{{ form.workaddr }}</h4>


      {{ form.workzip.errors }}
      <h4><label for="workzip" class="col-sm-0 control-label">Company Zipcode</label></h4>
      <h4>{{ form.workzip }}</h4>


    </div>



    <script type = "text/javascript">



    $(document).ready(function(){

    var compname = {{ name|safe }};
    var address = {{ address|safe }}

     $( "input#id_workname" ).autocomplete({
                            source: compname, 
                            minLength: 2
        });

     $( "input#id_workaddr" ).autocomplete({
                            source: address, 
                            minLength: 2
        });




    });
 

    </script>



    <input class="btn btn-lg btn-success" type="submit" value="Join Now">
  </form>



  <div class = "row marketing"> 


    {% for post in object_list%}
    <li>
    <h4 class="text-success"> <a class="text-success" href="mailto: {{post.email}}"> {{post.email}}</a>: {{post.homezip|safe}} &#8596; {{post.workname|safe}}, {{post.workaddr|safe}}, {{post.workzip|safe}} {{post.date|safe}}</h4>
    </li>

    {% endfor %}





    </div>


  <div class="footer">
    <p>&copy; Company 2014</p>
  </div>

</div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
  </html>